// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import { lazy } from "solid-js";

export const Index: Record<string, any> = {
  index: {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
  },
  utils: {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    component: lazy(() => import("src/registry/items/lib/utils")),
    files: [
      {
        path: "src/lib/utils.ts",
        type: "registry:lib",
        target: "",
      },
    ],
  },
};
